### ISSUE TITLE
Are there plans to make a code generator?

### ISSUE THREAD

**Issue by akxcv** [ipetkov/conch-parser#2]
Hi! Are you planning to implement code generation from a given AST? Or are there any other open source generators available?

**Comment by ipetkov** [comment]
Hi @akxcv! Could you give me a better example of the type of code generation you are looking for?

I had originally toyed with the idea of being able to serialize an arbitrary AST back to its code representation, but I quickly realized that the AST would have to largely avoid losing any kind of information during the parse (e.g. escaped characters, heredoc delimiters, etc.).

The usecase I had in mind there was for potentially linking back to the script source. I reached the conclusion that it would probably be better to track the source itself for diagnostic purposes (which hasn't been implemented yet) rather than try to rederive it.

That said, it *could* be possible to use a custom AST which carries extra bits of info, but I'm trying to get a better idea of what you're hoping to achieve before giving more advice!

**Comment by akxcv** [comment]
Sorry, I think I'd forgotten the use case I had in mind. Or, perhaps, I felt I needed code generation for something, but I don't.

I think I'll close this issue for now and reopen it if needed.
